module_files:
  - "modules/dashboardmodule.R"
  - "modules/cellcontentmodule.R"
  - "modules/immuneinterfacemodule.R"
  - "modules/groupsoverviewmodule.R"
  - "modules/survivalmodule.R"
  - "modules/immunomodulatormodule.R"
  - "modules/tilmodule.R"
  - "modules/immunefeaturesmodule.R"
  - "modules/iotargetmodule.R"
  - "modules/datainfomodule.R"
  - "modules/drivermodule.R"
  - "modules/subtypeclassifiermodule.R"
  - "modules/submodules.R"
  - "modules/distribution_plot_module.R"
  - "modules/model_selection_module.R"
  - "modules/insert_remove_element_module.R"
  - "modules/volcano_plot_module.R"

function_files:
  - "functions/create_db2.R"
  - "functions/transform.R"
  - "functions/drilldown.R"
  - "functions/utils.R"
  - "functions/boxplot.R"
  - "functions/heatmap.R"
  - "functions/kmplot.R"
  - "functions/histogram.R"
  - "functions/format.R"
  - "functions/scatterplot.R"
  - "functions/violinplot.R"
  - "functions/mosaicplot.R"
  - "functions/barplot.R"
  - "functions/subtype_classifier.R"
  - "functions/tablef_fun.R"
  - "functions/imageplot.R"
  - "functions/event_data_utils.R"

page_files:
  - "pages/aboutpage.R"
  - "pages/explorepage.R"
  - "pages/toolspage.R"
  - "pages/docspage.R"
  - "pages/resourcespage.R"

libraries:
  - "shinydashboard"
  - "plotly"
